hbsoo:
  server:
    id: 1000
    tcpHeader: THBS
    udpHeader: UHBS
    threadPoolSize:
      insideClient: 5
      insideServer: 10
      outsideServer: 20
    outsideServer:
      enable: true
      port: 5555
      protocol: "TCP,UDP,WEBSOCKET,HTTP"
    insideServers:
      - host: 192.168.1.104
        port: 6000
        type: gateway
        clientSize: 1
        weight: 10
        id: 1000

      - host: 192.168.1.104
        port: 6003
        type: hall
        clientSize: 1
        id: 2000

      - host: 192.168.1.104
        port: 6006
        type: room
        clientSize: 1
        id: 3000
# 配置日志输入级别
logging:
  level:
    com.hbsoo: debug
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss
