hbsoo:
  server:
    id: 3000
    tcpHeader: THBS
    udpHeader: UHBS
    threadPoolSize:
      innerClient: 5
      innerServer: 5
      outerServer: 5
    innerServers:
      - host: 192.168.1.104
        port: 6000
        type: gateway
        id: 1000

      - host: 192.168.1.104
        port: 6003
        type: hall
        id: 2000

      - host: 192.168.1.104
        port: 6006
        type: room
        id: 3000

# 配置日志输入级别
logging:
  level:
    com.hbsoo: debug
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss