hbsoo:
  server:
    id: 2000
    tcpHeader: THBS
    udpHeader: UHBS
    threadPoolSize:
      insideClient: 5
      insideServer: 5
      outsideServer: 5
    insideServers:
      - host: 192.168.1.104
        port: 6000
        type: gateway
        id: 1000

      - host: 192.168.1.104
        port: 6003
        type: hall
        id: 2000

      - host: 192.168.1.104
        port: 6006
        type: room
        id: 3000

# 配置日志输入级别
logging:
  level:
    com.hbsoo: debug
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss